### ISSUE TITLE
Create a bounds transform stream

### ISSUE THREAD

**Issue by nfroidure** [nfroidure/svg-pathdata#26]
Would allow to fix this issue https://github.com/nfroidure/svgicons2svgfont/issues/18

**Comment by NaridaL** [comment]
What exactly would the transformer do? I already have algorithms for calculatings bounds for arcs and beziers in a different, project, so I could have a look at this one.

**Comment by nfroidure** [comment]
Rethinking it, it wouldn't exactly be a transformer but rather a simple function.

Is this project open-source ? I could just use it if so.

**Comment by NaridaL** [comment]
A transformer could add a `command.bounds: {minx: number, maxx: number, miny: number, maxy: number}` to each command, but I guess there aren't many use cases where you want the bounds of individual commands. The project is theoretically open source (when I get around to uploading it), but it's pretty big and converting to and from is a bit of a hassle, so copying the relevant parts probably makes more sense than depending on it.

**Comment by NaridaL** [comment]
I started implementing a solution. I've written it as a transformer so that it works both on streams and synchronously . Would this work with what you need @nfroidure ? https://github.com/nfroidure/svg-pathdata/commit/f025bee61941bf842ff189ba6b21165bd714f612

**Comment by NaridaL** [comment]
![image](https://user-images.githubusercontent.com/10828874/29223926-8a42b066-7ec8-11e7-95fb-03f7902de64f.png)
Got the arcs to work...

**Comment by NaridaL** [comment]
![image](https://user-images.githubusercontent.com/10828874/29244864-25184946-7fc5-11e7-8717-dc3e24dac4b4.png)

**Comment by NaridaL** [comment]
I merged it into master
```ts
// Sync usage:
const bounds = new SVGPathData(svgPathString).getBounds()
// bounds: {minX: number, maxX: number, minY: number, maxY: number}

// async:
const bounds = SVGPathData.Transformer.CALCULATE_BOUNDS()
stream.pipe(new SVGPathData.Transformer(bounds))
// bounds has type TransformFunction & {minX: number, maxX: number, minY: number, maxY: number}
// so you can do bounds.minX etc. These values will be updated as svg commands are piped through the transformer. The transformer doesn't modify the commands.
```

Hmm, considering it now, I'm not entirely sure the async behavior makes sense... would it be better to have it output the current bounds on every read svg command?

**Comment by NaridaL** [comment]
So I'm integrating the new getBounds function into svgicons2svgfont...

"Test failed. Click to see diff."
*clicks* 
![image](https://user-images.githubusercontent.com/10828874/29248912-8b600c8e-8024-11e7-8a99-ad88eefed66f.png)
