### ISSUE TITLE
Node 4 support

### ISSUE THREAD

**Issue by jantimon** [nfroidure/svg-pathdata#29]
Hey,

I just saw that you are using the spread operator.
https://github.com/nfroidure/svg-pathdata/blob/master/src/SVGPathData.js#L88

Would it be possible to replace it?

The reason for my request is that I would like to provide a webpack plugin and webpack tries to support node 4+

Thanks :)

**Comment by NaridaL** [comment]
Unless @nfroidure wants to target an older ES version, I'd suggest just including a babel pass in your build process.

**Comment by nfroidure** [comment]
Hi,

I balance between the fact to keep the project up to date and a wider support. I have not that much time to maintain OSS projects currently so I group the most things I can when I take the time to commit.

@jantimon is staying to a prior version until you can switch to Node6 an option ?

**Comment by NaridaL** [comment]
@jantimon TypeScript is now configured to compile to es5 so it should work in node 4+.

**Comment by jantimon** [comment]
Wow cool thanks! :)
