### ISSUE TITLE
TypeScript conversion

### ISSUE THREAD

**Issue by NaridaL** [nfroidure/svg-pathdata#30]
Do you mind if I convert the codebase to TS? Shouldn't be much effort. Consumers shouldn't be affected. Also, I could compile to es5 which would solve #29.

**Comment by nfroidure** [comment]
Feel free to since you're the main maintainer of the repo. I'm always considering to use a typing system but balancing between TS, flow or another language that compiles to JS. Did you tried other language or only tried TS?

**Comment by NaridaL** [comment]
I've only worked with typescript. Flow looks to be very similar. Going by
github stars TS is far more popular though.

**Comment by NaridaL** [comment]
https://github.com/nfroidure/svg-pathdata/tree/tsconv

There are some changes though. "Classes" which can be called both with and without new don't work well with es6 class syntax, and even worse with TS, so the `new` keyword is now required.

Also with es6 export syntax you can't do module.exports = MyClass, so the module structure has now changed:

import {SVGPathData, SVGPathDataTransformer, SVGPathDataEncoder, SVGPathDataParser} from 'svg-pathdata';

**Comment by NaridaL** [comment]
@nfroidure I'm having issues with the metapak. I removed the postinstall script in the tsconv branch but that's just a temporary solution.
https://github.com/nfroidure/svg-pathdata/commit/f001d374c98954276b0915460986a8b0c797643a#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L23
The issues I'm having: 

- devDependencies for eslint and eslint-config-simplifield are being reset. (This isn't really related to ts conversion uh...)
- I added `lib` to .gitignore but that's getting reset
- I changed the lint script to `eslint && tslint`, but that's also getting reset. (I didn't convert the tests because the advantages are minor there and I'm not entirely sure how that works in conjunction with mocha)
- On a semi-related note, what was the reasoning for removing the /dist/ build? It makes it easy to test the lib without npm/node and the effort to maintain is basically zero? I added it back in this branch because I make use of it, but again, `dist` is being added to .gitignore.

I'm not sure how to solve this in the context of metapak? Don't overwrite existing values in the metapak-config? But then how does that differ from just having a template for new projects? Separate metapak-config module for TS projects?

**Comment by nfroidure** [comment]
@NaridaL indeed `metapak` is different from having a template for new project, its intent is to keep projects in sync with the latest changes of my developer tools in every projects I made.

The thing is I do not use TypeScript yet so I have no `metapak` plugin for it.

In the other hand, you took the control of this repo so I think the best for you is to eject metapak by simply removing the `metapak`, `metapak-nfroidure` packages and then remove the postinstall hook. This will prevent the behavior you described above.

**Comment by NaridaL** [comment]
Ok, removing metapak is what I ended up doing. If you end up having other TS projects adding it back in shouldn't be much of a problem. I merged tsconv into master.
