### ISSUE TITLE
Broken on node 10.0.0

### ISSUE THREAD

**Issue by alexander-akait** [nfroidure/svg-pathdata#33]
## Issue
I use `svgicons2svgfont` package in https://github.com/itgalaxy/webfont and this package broken on node 10.0.0. After debug i found event https://github.com/nfroidure/svg-pathdata/blob/master/src/SVGPathData.ts#L138 is not fires on node 10.0.0, but work good on other node version. I don't know maybe it is bug new node or something wrong inside package code.

I'm a gentledev i:
- [x] fully read the README recently
- [x] searched for existing issues
- [x] checked i'm up to date with the latest version of the project

### Expected behavior

Works.

### Actual behavior

Not works

### Debugging informations
- `node -v` result:
```
10.0.0
```

- `npm -v` result:
```
6.0.0
```
If the result is lower than 6.9.5, there is
 poor chances i even have a look to it. Please,
 use the last [NodeJS LTS version](https://nodejs.org/en/).

## Feature request

It is not feature.

### Feature description

It is not feature.

### Use cases

- [ ] I will/have implement the feature

**Comment by nfroidure** [comment]
@evilebottnawi I do not use this repository atm so not in my priorities to fix it (and I do not know how much time it should take). Feel free to PR if you got a fix. Also @NaridaL took the lead on this project so maybe he have an idea on why it breaks on Node10. Maybe that a new TypeScript build on Node10 can help ?

**Comment by evilebottnawi** [comment]
@nfroidure maybe, i will try

**Comment by evilebottnawi** [comment]
@pioug 
> I can only think of changing SVGPathData.encode/SVGPathData.parse to make them asynchronous OR implementing SVGPathDataEncoder/SVGPathDataParser without Transform and exposing synchronous methods.

I think it is require a lot of work, maybe we should do this in future. What about just use `process.nextTick` hack?

**Comment by nfroidure** [comment]
If I remind well using streams synchronously was a feature of Node in its early times. Maybe they expose another API to do so?

Anyway using streams to do synchronous work was conceptually ugly and it was the point of this issue: https://github.com/nfroidure/svg-pathdata/issues/31

That said, it was a bit of work and never took the time to do it. It should take something like a day or 2 I guess...

**Comment by evilebottnawi** [comment]
@pioug Do you have time on this? :smile:

**Comment by pioug** [comment]
Seems doable! I still to understand a bit TypeScript too! I will find some time this week.

**Comment by evilebottnawi** [comment]
@pioug awesome, very thanks!

**Comment by pioug** [comment]
I started here https://github.com/nfroidure/svg-pathdata/compare/master...pioug:sync-api. Tests are passing on Node 10. 

There is still a lot of things to do (write pure functions, update documentation, figure out what  `SVGPathDataTransformer` does 😬...)

**Comment by evilebottnawi** [comment]
@pioug friendly ping, status?

**Comment by unbywyd** [comment]
Hi guys! I ran into this problem when I plan to fix it? Ths

**Comment by NaridaL** [comment]
Sorry for the delay. I removed the stream dependency entirely. I've also patched svgicons2svgfont to use the updated version. Please close if it works as expected now.
