### ISSUE TITLE
move rollup-plugin-terser to devDependencies

### ISSUE THREAD

**Issue by leon** [nfroidure/svg-pathdata#46]
## Issue

I'm a gentledev i:
- [x] fully read the README recently
- [x] searched for existing issues
- [x] checked i'm up to date with the latest version of the project

### Expected behavior
To not get any warnings for rollup
warning "svg-pathdata > rollup-plugin-terser@5.3.0" has unmet peer dependency "rollup@>=0.66.0 <3".

### Actual behavior
Get warning when installing svg-pathdata

### Solution
move `rollup-plugin-terser` to devDependencies in package.json

**Comment by arniu** [comment]
@nfroidure Would you merge it?

**Comment by nfroidure** [comment]
Yep, thanks for the reminder

**Comment by leon** [comment]
Any update on this?

**Comment by kaidjohnson** [comment]
Now that this has been merged to master, can we get a 5.0.5 release so the fix can be realized downstream?

**Comment by nfroidure** [comment]
@kaidjohnson not that much time to allocate to those projects (and gh sponsors seems desperately empty ;) ) so sorry for the delay. Did it right now.
