### ISSUE TITLE
Wrong source map sources path

### ISSUE THREAD

**Issue by OpportunityLiu** [nfroidure/svg-pathdata#60]
## Issue

I'm a gentledev i:
- [x] fully read the README recently
- [x] searched for existing issues
- [x] checked i'm up to date with the latest version of the project

### Expected behavior

Correct source map

### Actual behavior

Duplicate `src` in source map `sources`, lead to `Failed to parse source map from 'XX\node_modules\svg-pathdata\src\src\mathUtils.ts' file: Error: ENOENT: no such file or directory, open 'XX\node_modules\svg-pathdata\src\src\mathUtils.ts'`

https://unpkg.com/browse/svg-pathdata@6.0.2/lib/SVGPathData.cjs.map
![image](https://user-images.githubusercontent.com/13471233/133880627-9ead969c-0816-49e4-8a1e-dbe8b3bc2472.png)

### Debugging informations
- `node -v` result:
```
<paste here>
```

- `npm -v` result:
```
<paste here>
```
If the result is lower than 6.9.5, there is
 poor chances i even have a look to it. Please,
 use the last [NodeJS LTS version](https://nodejs.org/en/).

**Comment by pioug** [comment]
Please check v6.0.3. Share an example if it's still not working because I am not really familiar with sourcemaps.
